name: LearnGo

on:
  push:
    branches: [main]
    

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Build and Push DockerFile
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          cd src/
          sudo docker build -t thaily/learngo .
          sudo docker push thaily/learngo
  deploy:
    needs: docker 
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/learngo:latest
      - name: Delete old container
        run: sudo docker rm -f learngo
      - name: Run docker container
        run: |
          cd ~
          sudo docker run -d -p 8080:8080 --name learngo --env-file .env thaily/learngo
